Repository educodar/web, pull requests merged in 2019-08, with the labels that each got.

#65 Bring master files to feature/homepage
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/pull_request_template.md
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: keeping in sync

#67 Update `feature/homepage` with `dev` & `master` changes
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/pull_request_template.md
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: keeping in sync

#69 Closes #66
  src/components/SEO/__tests__/index.js
  src/pages/__tests__/__snapshots__/index.js.snap
  src/pages/__tests__/index.js
  src/pages/index.js
Labels: bug

#70 Sync `dev` and `feature/homepage`
  src/components/SEO/__tests__/index.js
  src/pages/__tests__/__snapshots__/index.js.snap
  src/pages/__tests__/index.js
Labels: bug, keeping in sync

#75 Fixes #66 (SEO component test FAIL: not rendering correctly bug)
  src/components/SEO/__tests__/index.js
  src/pages/__tests__/__snapshots__/index.js.snap
  src/pages/__tests__/index.js
  src/pages/index.js
Labels: bug

#81 Feature/homepage
  .DS_Store
  package.json
  src/.DS_Store
  src/atoms/Button/button.module.css
  src/atoms/Button/index.js
  src/atoms/FeaturedSection/featuredSection.module.css
  src/atoms/FeaturedSection/index.js
  src/atoms/HeroImage/index.js
  src/atoms/HeroImage/index.module.css
  src/atoms/VerticalSpacing/index.js
  src/atoms/VerticalSpacing/verticalSpacing.module.css
  src/components/Articles/article-template.js
  src/components/Articles/articles-section.js
  src/components/Articles/styles.css
  src/components/Button/button.js
  src/components/Button/styles.css
  src/components/Footer/footer.js
  src/components/Footer/styles.css
  src/components/Header/styles.css
  src/components/Hero/hero.js
  src/components/Hero/styles.css
  src/images/computer-line.png
  src/images/computer-line@2x.png
  src/images/computer-line@3x.png
  src/images/students.jpg
  src/images/thoughtworks_logo.png
  src/images/thoughtworks_logo@2x.png
  src/images/thoughtworks_logo@3x.png
  src/index.css
  src/layouts/__tests__/__snapshots__/index.js.snap
  src/layouts/index.js
  src/molecules/Hero/hero.module.css
  src/molecules/Hero/index.js
  src/organisms/Footer/footer.module.css
  src/organisms/Footer/index.js
  src/organisms/Header/header.module.css
  src/organisms/Header/index.js
  src/organisms/Main/index.js
  src/organisms/Main/main.module.css
  src/pages/__tests__/__snapshots__/index.js.snap
  src/pages/index.js
  src/utils/typography.js
Labels: help wanted, user story
