Repository educodar/web, pull requests merged in 2019-07, with the labels that each got.

#15 Adding first unit test
  .editorconfig
  __mocks__/file-mock.js
  __mocks__/gatsby.js
  jest-preprocess.js
  jest.config.js
  loadershim.js
  package-lock.json
  package.json
  src/pages/__tests__/__snapshots__/index.test.js.snap
  src/pages/__tests__/index.test.js
  src/pages/index.js
Labels: developer experience

#19 Add team page & CONTRIBUTING.md
  CONTRIBUTING.md
  src/pages/equipe/index.jsx
  static/humans.txt
Labels: developer experience, enhancement

#20 Add basic team page & CONTRIBUTING.md from dev
  CONTRIBUTING.md
  src/pages/equipe/index.jsx
  static/humans.txt
Labels: developer experience, enhancement

#21 Feature/google site verification
  README.md
  gatsby-config.js
  package-lock.json
  package.json
  src/html.js
  src/layouts/index.js
Labels: developer experience

#22 Added <meta> on Helmet & tests
  package.json
  src/components/Layout/__snapshots__/index.test.js.snap
  src/components/Layout/index.js
  src/components/Layout/index.test.js
  src/layouts/index.js
  src/pages/__snapshots__/index.test.js.snap
  src/pages/equipe/__snapshots__/index.test.js.snap
  src/pages/equipe/index.js
  src/pages/equipe/index.jsx
  src/pages/equipe/index.test.js
  src/pages/index.js
  src/pages/index.test.js
Labels: enhancement

#23 Add Google Site Verification, React Helmet & other stuff
  README.md
  gatsby-config.js
  package-lock.json
  package.json
  src/components/Layout/__snapshots__/index.test.js.snap
  src/components/Layout/index.js
  src/components/Layout/index.test.js
  src/html.js
  src/pages/__snapshots__/index.test.js.snap
  src/pages/equipe/__snapshots__/index.test.js.snap
  src/pages/equipe/index.js
  src/pages/equipe/index.jsx
  src/pages/equipe/index.test.js
  src/pages/index.js
  src/pages/index.test.js
Labels: enhancement

#25 Update dev using master
  package-lock.json
  package.json
Labels: keeping in sync

#29 Closes #28 - Add Docker support
  .devcontainer/devcontainer.json
  .dockerignore
  .editorconfig
  .gitattributes
  .gitignore
  .prettierrc
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile
  LICENSE
  Makefile
  README.md
  docker-compose.debug.yml
  docker-compose.yml
  gatsby-config.js
  jest-preprocess.js
  jest.config.js
  loadershim.js
  package-lock.json
  package.json
  src/components/Layout/index.js
  src/components/Layout/index.test.js
  src/layouts/__tests__/__snapshots__/index.js.snap
  src/layouts/__tests__/index.js
  src/layouts/index.js
  src/pages/__tests__/__snapshots__/equipe.js.snap
  src/pages/__tests__/__snapshots__/index.js.snap
  src/pages/__tests__/equipe.js
  src/pages/__tests__/index.js
  src/pages/equipe.js
  src/pages/equipe/index.js
  src/pages/equipe/index.test.js
  src/pages/index.js
  src/pages/index.test.js
Labels: developer experience, enhancement

#34 Bring master last changes to feature/cypress branch
  .devcontainer/devcontainer.json
  .dockerignore
  .editorconfig
  .gitattributes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  .prettierrc
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile
  LICENSE
  Makefile
  README.md
  docker-compose.debug.yml
  docker-compose.yml
  gatsby-config.js
  jest-preprocess.js
  jest.config.js
  loadershim.js
  package-lock.json
  package.json
  renovate.json
  src/components/Layout/index.js
  src/components/Layout/index.test.js
  src/layouts/__tests__/__snapshots__/index.js.snap
  src/layouts/__tests__/index.js
  src/layouts/index.js
  src/pages/__tests__/__snapshots__/equipe.js.snap
  src/pages/__tests__/__snapshots__/index.js.snap
  src/pages/__tests__/equipe.js
  src/pages/__tests__/index.js
  src/pages/equipe.js
  src/pages/equipe/index.js
  src/pages/equipe/index.test.js
  src/pages/index.js
  src/pages/index.test.js
  static/googled6815cf0bb7979e2.html
Labels: keeping in sync

#35 Sync dev and master branches
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  renovate.json
Labels: keeping in sync

#36 Pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: developer experience

#38 Consolidate package*.json and more changes
  .devcontainer/devcontainer.json
  Dockerfile
  README.md
  package-lock.json
  package.json
Labels: developer experience, enhancement, keeping in sync
